name: The End Of Television
favicon: null
layout_spectrum: 0.33048
typography_spectrum: 0.55566
title: The End Of Television As We Know It
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f2f0'
    - '#111113'
    - '#574037'
    - '#86bbd5'
    - '#867066'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
